spring.application.name=demo
server.port=9090
# PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_tracker
spring.datasource.username=postgres
spring.datasource.password=Indium@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate SQL Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Local Ollama AI Configuration
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2:1b